### ISSUE TITLE
Organize example folder structure for archive upload by interface slug?

### ISSUE THREAD

**Issue by amickan** [DIAGNijmegen/rse-grand-challenge-forge#10]
If an archive item consists of multiple files, the example cases are currently organized into folders by case. The upload script then relies on the user listing the files in `EXPECTED_CASES` in the correct order (file for ci-1 first, file for ci-2 second) per case. It might be more fool-proof to have subfolders per case for each interface with each folder containing only one file. The file paths in `EXPECTED_CASES` would then be self explanatory. This is also how the input is presented to the algorithms etc, so would be nicely consistent. 

Just a suggestion though ;-)

**Comment by chrisvanrun** [comment]
Good suggestion! I even had that as the initial structure! However, I am pretty sure the current format is far more common to see for structured cases: just a directory per case.

Of course, that is just an assumption and likely no two users will have the same data structure. I opted for simplicity here, it should be pretty straight-forward for people to generate a list of files per case. Instead of including pointers to slugs I have explicitly made a `map_case_content_to_interfaces()` as to highlight that there is an ordinal step in there.

**Comment by amickan** [comment]
Ok, fair enough. If it turns out that organizers have issues with this, we can always change it in the future. For now we just need to make sure that we explain to them that the order matters.

**Comment by chrisvanrun** [comment]
Also, fools are ingenious.
